import type { DemoProfile } from "./types";

/**
 * India profile — same pinned org id/slug, India-flavored data.
 *
 * Holiday dates use a fixed `MM-DD` per row, combined with the seed's
 * `CYCLE_YEAR` at insert time. The fixed-date holidays (Republic Day,
 * Independence Day, Christmas) are stable across years; the lunar/lunisolar
 * holidays (Holi, Ugadi, Ram Navami, Ganesh Chaturthi, Dussehra, Diwali)
 * are pinned to the **2026 Gregorian dates** for demo determinism. Re-pin
 * annually when seeding for a different calendar year — `MM-DD` is the
 * shape the existing seed reads, and Gregorian drift on lunar holidays is
 * accepted as a known demo limitation rather than a wired calendar.
 */
export const INDIA_PROFILE: DemoProfile = {
  key: "india",
  org: {
    name: "Bharat Tech Solutions Pvt Ltd",
    legalName: "Bharat Tech Solutions Private Limited",
    domain: "bharattech.demo",
    primaryColor: "#FF6F00",
    timezone: "Asia/Kolkata",
    locale: "en-IN",
    currency: "INR",
    weekStart: 1,
    billingEmail: "billing@bharattech.demo",
  },
  locations: [
    {
      name: "Bengaluru HQ",
      code: "BLR",
      city: "Bengaluru",
      state: "KA",
      country: "IN",
      tz: "Asia/Kolkata",
    },
    {
      name: "Mumbai Office",
      code: "MUM",
      city: "Mumbai",
      state: "MH",
      country: "IN",
      tz: "Asia/Kolkata",
    },
    {
      name: "Hyderabad Office",
      code: "HYD",
      city: "Hyderabad",
      state: "TG",
      country: "IN",
      tz: "Asia/Kolkata",
    },
    {
      name: "Delhi NCR Office",
      code: "DEL",
      city: "New Delhi",
      state: "DL",
      country: "IN",
      tz: "Asia/Kolkata",
    },
    {
      name: "Chennai Office",
      code: "MAA",
      city: "Chennai",
      state: "TN",
      country: "IN",
      tz: "Asia/Kolkata",
    },
    {
      name: "Remote",
      code: "RMT",
      city: "Remote",
      state: null,
      country: "IN",
      tz: "Asia/Kolkata",
    },
  ],
  departments: [
    "Engineering",
    "Product",
    "Design",
    "Sales",
    "Marketing",
    "Human Resources",
    "Finance",
    "Customer Success",
  ],
  designations: [
    { name: "Intern", level: 1 },
    { name: "Associate", level: 2 },
    { name: "Software Engineer", level: 3 },
    { name: "Senior Software Engineer", level: 4 },
    { name: "Staff Engineer", level: 5 },
    { name: "Team Lead", level: 5 },
    { name: "Engineering Manager", level: 6 },
    { name: "Senior Manager", level: 6 },
    { name: "Analyst", level: 3 },
    { name: "Senior Analyst", level: 4 },
    { name: "Coordinator", level: 2 },
    { name: "Director", level: 7 },
    { name: "Vice President", level: 8 },
  ],
  firstNames: [
    "Arjun",
    "Priya",
    "Aanya",
    "Rohan",
    "Sneha",
    "Karthik",
    "Divya",
    "Vikram",
    "Ananya",
    "Aditya",
    "Pooja",
    "Rahul",
    "Kavya",
    "Manish",
    "Nikhil",
    "Rashmi",
    "Sanjay",
    "Tara",
    "Vijay",
    "Yash",
    "Aisha",
    "Bhavna",
    "Chetan",
    "Deepa",
    "Eshan",
    "Farhan",
    "Gauri",
    "Harsh",
    "Indira",
    "Jay",
    "Kiran",
    "Lata",
    "Meera",
    "Neha",
    "Omkar",
    "Pranav",
    "Rakesh",
    "Sita",
    "Tanvi",
    "Uday",
  ],
  lastNames: [
    "Patel",
    "Sharma",
    "Kumar",
    "Reddy",
    "Iyer",
    "Singh",
    "Gupta",
    "Verma",
    "Joshi",
    "Mehta",
    "Nair",
    "Pillai",
    "Bhatt",
    "Rao",
    "Kapoor",
    "Bansal",
    "Chopra",
    "Desai",
    "Khanna",
    "Malhotra",
    "Mishra",
    "Pandey",
    "Saxena",
    "Tiwari",
    "Yadav",
    "Agarwal",
    "Banerjee",
    "Chatterjee",
    "Ghosh",
  ],
  holidayCalendar: { name: "India Public Holidays", code: "IN-PUB" },
  holidays: [
    { md: "01-01", name: "New Year's Day" },
    { md: "01-26", name: "Republic Day" },
    { md: "03-04", name: "Holi" },
    { md: "03-19", name: "Ugadi / Gudi Padwa" },
    { md: "03-27", name: "Ram Navami" },
    { md: "08-15", name: "Independence Day" },
    { md: "09-15", name: "Ganesh Chaturthi" },
    { md: "10-20", name: "Dussehra" },
    { md: "11-08", name: "Diwali" },
    { md: "12-25", name: "Christmas Day" },
  ],
  logins: [
    {
      role: "super_admin",
      emailLocal: "superadmin",
      first: "Aarav",
      last: "Sharma",
      portal: "admin",
      dept: "Engineering",
      desig: "Director",
    },
    {
      role: "hr_admin",
      emailLocal: "hr",
      first: "Priya",
      last: "Reddy",
      portal: "admin",
      dept: "Human Resources",
      desig: "Senior Manager",
    },
    {
      role: "manager",
      emailLocal: "manager",
      first: "Vikram",
      last: "Iyer",
      portal: "admin",
      dept: "Engineering",
      desig: "Engineering Manager",
    },
    {
      role: "employee",
      emailLocal: "employee",
      first: "Anjali",
      last: "Patel",
      portal: "employee",
      dept: "Engineering",
      desig: "Software Engineer",
    },
  ],
  announcementTitles: [
    "Welcome to the new Staffly portal!",
    "Independence Day flag hoisting — Aug 15 at 8 AM",
    "Updated hybrid-work policy (please acknowledge)",
    "Diwali week schedule — office closed Nov 7–9",
    "Annual appraisal cycle opens Monday",
    "Draft: Onam celebrations",
    "New hires joining this month — say hello!",
    "Security awareness training due (please acknowledge)",
  ],
  orgDocumentTitles: [
    "Employee Handbook 2026",
    "Code of Conduct",
    "Information Security Policy",
    "Hybrid Work Policy",
    "Reimbursement Guide (INR)",
    "Leave Policy (Casual / Sick / Earned)",
    "Health & Safety Guidelines",
    "Provident Fund & Benefits Overview",
  ],
};
