import type { DemoProfile } from "./types";

/**
 * US profile — the default. Matches the historical Acme Corporation seed
 * verbatim; extracted from `seed-demo.ts` constants so the file can read
 * from the same shape as any other profile.
 */
export const US_PROFILE: DemoProfile = {
  key: "us",
  org: {
    name: "Acme Corporation",
    legalName: "Acme Corporation, Inc.",
    domain: "acme.demo",
    primaryColor: "#4F46E5",
    timezone: "America/New_York",
    locale: "en-US",
    currency: "USD",
    weekStart: 1,
    billingEmail: "billing@acme.demo",
  },
  locations: [
    {
      name: "San Francisco HQ",
      code: "SFO",
      city: "San Francisco",
      state: "CA",
      country: "US",
      tz: "America/Los_Angeles",
    },
    {
      name: "New York Office",
      code: "NYC",
      city: "New York",
      state: "NY",
      country: "US",
      tz: "America/New_York",
    },
    {
      name: "Austin Office",
      code: "AUS",
      city: "Austin",
      state: "TX",
      country: "US",
      tz: "America/Chicago",
    },
    {
      name: "London Office",
      code: "LON",
      city: "London",
      state: "England",
      country: "GB",
      tz: "Europe/London",
    },
    {
      name: "Bangalore Office",
      code: "BLR",
      city: "Bengaluru",
      state: "KA",
      country: "IN",
      tz: "Asia/Kolkata",
    },
    {
      name: "Remote",
      code: "RMT",
      city: "Remote",
      state: null,
      country: "US",
      tz: "America/New_York",
    },
  ],
  departments: [
    "Engineering",
    "Product",
    "Design",
    "Sales",
    "Marketing",
    "Human Resources",
    "Finance",
    "Customer Success",
  ],
  designations: [
    { name: "Intern", level: 1 },
    { name: "Associate", level: 2 },
    { name: "Software Engineer", level: 3 },
    { name: "Senior Software Engineer", level: 4 },
    { name: "Staff Engineer", level: 5 },
    { name: "Team Lead", level: 5 },
    { name: "Engineering Manager", level: 6 },
    { name: "Senior Manager", level: 6 },
    { name: "Analyst", level: 3 },
    { name: "Senior Analyst", level: 4 },
    { name: "Coordinator", level: 2 },
    { name: "Director", level: 7 },
    { name: "Vice President", level: 8 },
  ],
  firstNames: [
    "Olivia",
    "Liam",
    "Emma",
    "Noah",
    "Ava",
    "Ethan",
    "Sophia",
    "Mason",
    "Isabella",
    "Lucas",
    "Mia",
    "Aiden",
    "Amelia",
    "Kai",
    "Harper",
    "Arjun",
    "Priya",
    "Wei",
    "Mei",
    "Diego",
    "Sofia",
    "Omar",
    "Layla",
    "Tariq",
    "Nina",
    "Hugo",
    "Zara",
    "Mateo",
    "Yuki",
    "Ravi",
    "Elena",
    "Marcus",
    "Aisha",
    "Felix",
    "Lena",
    "Carlos",
    "Ingrid",
    "Sanjay",
    "Chloe",
    "Theo",
  ],
  lastNames: [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Wilson",
    "Anderson",
    "Patel",
    "Nguyen",
    "Kim",
    "Chen",
    "Singh",
    "Kumar",
    "Ali",
    "Khan",
    "Okafor",
    "Mwangi",
    "Schmidt",
    "Rossi",
    "Yamamoto",
    "Tanaka",
    "Andersson",
  ],
  holidayCalendar: { name: "US Public Holidays", code: "US-PUB" },
  holidays: [
    { md: "01-01", name: "New Year's Day" },
    { md: "01-15", name: "Martin Luther King Jr. Day" },
    { md: "02-19", name: "Presidents' Day" },
    { md: "05-27", name: "Memorial Day" },
    { md: "06-19", name: "Juneteenth" },
    { md: "07-04", name: "Independence Day" },
    { md: "09-02", name: "Labor Day" },
    { md: "11-11", name: "Veterans Day" },
    { md: "11-28", name: "Thanksgiving" },
    { md: "11-29", name: "Day after Thanksgiving" },
    { md: "12-24", name: "Christmas Eve" },
    { md: "12-25", name: "Christmas Day" },
  ],
  logins: [
    {
      role: "super_admin",
      emailLocal: "superadmin",
      first: "Sasha",
      last: "Admin",
      portal: "admin",
      dept: "Engineering",
      desig: "Director",
    },
    {
      role: "hr_admin",
      emailLocal: "hr",
      first: "Hana",
      last: "Reyes",
      portal: "admin",
      dept: "Human Resources",
      desig: "Senior Manager",
    },
    {
      role: "manager",
      emailLocal: "manager",
      first: "Marcus",
      last: "Lee",
      portal: "admin",
      dept: "Engineering",
      desig: "Engineering Manager",
    },
    {
      role: "employee",
      emailLocal: "employee",
      first: "Alex",
      last: "Doe",
      portal: "employee",
      dept: "Engineering",
      desig: "Software Engineer",
    },
  ],
  announcementTitles: [
    "Welcome to the new Staffly portal!",
    "Q3 All-Hands — Thursday 4pm",
    "Updated remote-work policy (please acknowledge)",
    "Office closed for Thanksgiving week",
    "Annual benefits enrollment opens Monday",
    "Draft: Holiday party planning",
    "New hires joining this month — say hello!",
    "Security awareness training due (please acknowledge)",
  ],
  orgDocumentTitles: [
    "Employee Handbook 2026",
    "Code of Conduct",
    "Information Security Policy",
    "Remote Work Policy",
    "Expense Reimbursement Guide",
    "Leave Policy",
    "Health & Safety Guidelines",
    "Benefits Overview",
  ],
};
